export interface MockTender {
  id: string;
  title: string;
  buyerName: string;
  country: string;
  deadline: string;
  estimatedValue: number | null;
  currency: string;
  score: number;
  matchBand: 'strong' | 'worth-reviewing' | 'low-priority' | 'not-recommended';
  status: 'open' | 'deadline-soon' | 'expired' | 'cancelled' | 'updated';
  fitTags: string[];
  hasRisk: boolean;
  source: string;
}

export const mockTenders: MockTender[] = [
  {
    id: 'tender-001',
    title: 'Cloud case management',
    buyerName: 'Ministry of Health',
    country: 'Singapore',
    deadline: '2026-09-28',
    estimatedValue: 200000,
    currency: 'SGD',
    score: 91,
    matchBand: 'strong',
    status: 'open',
    fitTags: ['React', 'AWS'],
    hasRisk: false,
    source: 'govtender.sg',
  },
  {
    id: 'tender-002',
    title: 'Mobile service platform',
    buyerName: 'State Bank',
    country: 'Singapore',
    deadline: '2026-10-02',
    estimatedValue: 100000,
    currency: 'SGD',
    score: 84,
    matchBand: 'strong',
    status: 'open',
    fitTags: ['React'],
    hasRisk: false,
    source: 'govtender.sg',
  },
  {
    id: 'tender-003',
    title: 'Data integration support',
    buyerName: 'Transportation Authority',
    country: 'Singapore',
    deadline: '2026-09-18',
    estimatedValue: 75000,
    currency: 'SGD',
    score: 73,
    matchBand: 'worth-reviewing',
    status: 'deadline-soon',
    fitTags: ['Node.js'],
    hasRisk: true,
    source: 'govtender.sg',
  },
  {
    id: 'tender-004',
    title: 'E-commerce platform modernization',
    buyerName: 'Retail Corp Asia',
    country: 'Malaysia',
    deadline: '2026-10-15',
    estimatedValue: 350000,
    currency: 'MYR',
    score: 68,
    matchBand: 'worth-reviewing',
    status: 'open',
    fitTags: ['React', 'Node.js', 'PostgreSQL'],
    hasRisk: false,
    source: 'tenders.gov.my',
  },
  {
    id: 'tender-005',
    title: 'Supply chain analytics dashboard',
    buyerName: 'Logistics Network Southeast',
    country: 'Thailand',
    deadline: '2026-09-25',
    estimatedValue: null,
    currency: 'THB',
    score: 56,
    matchBand: 'low-priority',
    status: 'open',
    fitTags: ['Vue.js', 'Python'],
    hasRisk: true,
    source: 'e-bidding.go.th',
  },
  {
    id: 'tender-006',
    title: 'Healthcare records system',
    buyerName: 'Jakarta Medical Services',
    country: 'Indonesia',
    deadline: '2026-08-30',
    estimatedValue: 500000,
    currency: 'IDR',
    score: 42,
    matchBand: 'not-recommended',
    status: 'expired',
    fitTags: ['Java', 'AWS'],
    hasRisk: true,
    source: 'lpse.go.id',
  },
  {
    id: 'tender-007',
    title: 'Government portal upgrade phase 2',
    buyerName: 'Ministry of Communications',
    country: 'Vietnam',
    deadline: '2026-11-10',
    estimatedValue: 650000,
    currency: 'VND',
    score: 79,
    matchBand: 'worth-reviewing',
    status: 'updated',
    fitTags: ['React', 'TypeScript', 'AWS'],
    hasRisk: false,
    source: 'thauruong.gov.vn',
  },
  {
    id: 'tender-008',
    title: 'Mobile banking security audit',
    buyerName: 'Central Bank Philippines',
    country: 'Philippines',
    deadline: '2026-10-08',
    estimatedValue: 120000,
    currency: 'PHP',
    score: 88,
    matchBand: 'strong',
    status: 'open',
    fitTags: ['Security', 'Python', 'Node.js'],
    hasRisk: false,
    source: 'procurement.bsp.gov.ph',
  },
  {
    id: 'tender-009',
    title: 'Educational platform for rural schools',
    buyerName: 'Department of Education',
    country: 'Cambodia',
    deadline: '2026-12-01',
    estimatedValue: 280000,
    currency: 'USD',
    score: 65,
    matchBand: 'worth-reviewing',
    status: 'open',
    fitTags: ['React', 'Accessibility', 'i18n'],
    hasRisk: false,
    source: 'moe.gov.kh',
  },
  {
    id: 'tender-010',
    title: 'IoT sensor network for water quality',
    buyerName: 'Environmental Protection Bureau',
    country: 'Myanmar',
    deadline: '2026-09-20',
    estimatedValue: 450000,
    currency: 'USD',
    score: 72,
    matchBand: 'worth-reviewing',
    status: 'open',
    fitTags: ['IoT', 'Python', 'AWS', 'Real-time analytics'],
    hasRisk: true,
    source: 'mepe.gov.mm',
  },
];
